//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WesleyTesteGol.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        public int Codigo { get; set; }
        public string Modelo { get; set; }
        public int QuantidadePassageiros { get; set; }
        public System.DateTime DataCriacaoRegistro { get; set; }
    }
}
